code_all <- code_all %>% 
  mutate(
    MENTION = case_when(
      grepl("Adriana Ventura|Adriana Miguel|Adriana Vemtura|adriventurasp", TEXT) ~ "Adriana Ventura",
      grepl("Alê Silva|AlêSilvaOficial|alesilva.oficial|alesilva_38", TEXT) ~ "Alê Silva",
      grepl("Alice Portugal|depaliceportugal|Alice_Portugal", TEXT) ~ "Alice Portugal",
      grepl("Aline Gurgel|dep_alinegurgel|Aline gurjel|Aline Paranhos Varonil|Alline Gurgel|Alinne Gurgel", TEXT) ~ "Aline Gurgel",
      grepl("Aline Sleutjes|AlineSleutjesOficial|Aline Sletjes|Aline Sluetjes|Aline Sleutje|Aline Sleutjs|Aline Sluetjs|Aline Sluetje|aline seutjes|aline sletjes|aline sleujes|aline sleutes", TEXT) ~ "Aline Sleutjes",
      grepl("Ângela Amin|DeputadaAngela|angelaaminoficial|Angela Amim|Ângela amim|Angela Anim|Angela Anin", TEXT) ~ "Ângela Amin",
      grepl("Áurea Carolina|aureacarolinax|Área Carolina|Áurea Karolina|Aura Carolina|aurea carol|auria carol", TEXT) ~ "Áurea Carolina",
      grepl("Benedita da Silva|instadabene|dasilvabenedita|Beneditta da Silva|Benedita Silva|Bené da Silva|Benedita", TEXT) ~ "Benedita da Silva",
      grepl("Bia Cavassa|Bia Cavasa|Bia Cavaça|Bia cassava|Bia caçava", TEXT) ~ "Bia Cavassa",
      grepl("Bia Kicis|Bia Kisses|Bia Kycis|Bia Kices|Bia Kyces|Bia Kiss|Bia Kics|Bia quicis|Bia kisis|Bia kissis", TEXT) ~ "Bia Kicis",
      grepl("Bruna Furlan|depbrunafurlan|Bruna Furlan Deputada Federal|Bruna Furlam|Bruna Frulam", TEXT) ~ "Bruna Furlan",
      grepl("Carla Dickson|carladicksonrn|carladicksonoficial|Carla Dikson|Carla Dicson|Carla Dicksson|Carla Dicsson|Carla Diksson|Carla Diquisson|Karla Dikson|karla Dickson", TEXT) ~ "Carla Dickson",
      grepl("Carla Zambelli|CarlaZambelli38|carla.zambelli|nasruastv|Carla Zambeli|Zambelli|Zambeli|Karla Zambeli|Karla Zambelli|Carla Sambeli|Karla Sambeli", TEXT) ~ "Carla Zambelli",
      grepl("Carmen Zanotto|carmenzanotto_lages|carmen_zanotto|Carmem Zanotto|Carmem Zanoto|Carmen Zanoto|Carmem Sanoto|Carmen Sanoto", TEXT) ~ "Carmen Zanotto",
      grepl("Caroline de Toni|CarolDeToni|Carolini de Toni|Caroline detoni|Carolina de toni|Caroline Detone|Caroline di Toni|Caroline de Tone", TEXT) ~ "Carolina de Toni",
      grepl("Celina Leão|BateBolacomCelinaLeão|Cellina Leão|Celine Leão|Selina Leão|Seline Leão", TEXT) ~ "Celina Leão",
      grepl("Chris Tonietto|ToniettoChris|Cris Tonietto|Cris Tonieto|Chris Tonieto|Kris Tonieto|Kris Tonietto", TEXT) ~ "Chris Tonietto",
      grepl("Christiane de Souza Yared|Christiane Yared|Cristiane Yared|Cristiane Iared|Christiane Iared|Christiani Yared|Cristiani Iared|Cristiani Yared", TEXT) ~ "Christiane de Souza",
      grepl("Clarissa Garotinho|dep_clarissa|ClarissaGarotinho1|Clarissa Garotinha|Clarice Garotinho|Clarisse Garotinho|Filha do Garotinho|Clarisa Garotinho", TEXT) ~ "Clarissa Garotinho",
      grepl("Daniela do Waguinho|deputadadanieladowaguinho|Daniella do Waguinho|Daniella do Vaguinho|Daniela Waguinho|Daniela Vaguinho|Daniella Waguinho|Daniella Vaguinho|Danela do Vaguinho|Daniela do Vaguinho", TEXT) ~ "Daniela do Waguinho",
      grepl("Drª. Soraya Manato|DraManato|sorayamanato|Soraya Manato|Soraia Manato|Soraia Manatto|Dra. Soraia Manato|Dra Soraya Manato", TEXT) ~ "Soraya Manato",
      grepl("Dulce Miranda|dulcemirandato|dulcemiranda_to|Duce miranda|Dulci Miranda", TEXT) ~ "Dulce Miranda",
      grepl("Edna Henrique|ednahenriqueoficial|ednahenrique45|Edina Miranda|Edyna Miranda|Edina Henrique|Edyna Henrique", TEXT) ~ "Edna Henrique",
      grepl("Elcione Barbalho|Elcyone Barbalho|Helcione Barbalho|Elcione Barbalio", TEXT) ~ "Elcione Barbalho",
      grepl("Erika Kokay|Erica Cocai|Erica Cocay|Erika Cocai|Erika Kokai|Erica Kokay|Erica Cokay", TEXT) ~ "Erika Kokay",
      grepl("Fernanda Melchionna|fernandapsol|Fernanda Melchiona|Fernanda Melciona|Fernanda Melcionna|Fernanda Melxiona", TEXT) ~ "Fernanda Melchionna",
      grepl("Flavia Arruda|flaviaarrudadf|Flavia Aruda|Flávia Morais|flaviamorais1212|depflaviamorais|Flávia Moraes", TEXT) ~ "Flavia Arruda",
      grepl("Flordelis|flordeliscantora|depflordelis|Flor de Lis|Flordilis|Flor di Lis|Flordeliz|Flor de liz|flôr-delis", TEXT) ~ "Flordelis",
      grepl("Geovania de Sá|Geovânia Sá|Geovana de Sá|Giovana de Sá|Giovânia de Sá|Giovanea de Sá|Giovania de Sá|Geovanea de Sá", TEXT) ~ "Geovania de Sá",
      grepl("Gleisi Hoffmann|agleisihoffmann|Gleisi Hofmann|Gleisi Hofman|Gleisi Hoffman|Gleisi Rofiman|Gleice Rofiman|Gleice Rofimam|Gleici Hoffmann|Gleisi Lula|Gleici Hofmann|Gleici Hofman|Gleici Hoffman|Gleise Hoffmann|Gleise Hofmann|Gleise Hofman|Gleise Hoffman", TEXT) ~ "Gleisi Hoffmann",
      grepl("Gorete Pereira|Deputada Gorete Pereira|D_GoretePereira|dep_goretepereira|Gorette Pereira|Deputada Gorette Pereira|Gorrete Pereira", TEXT) ~ "Gorete Pereira",
      grepl("Greyce Elias|Greice Elias|Gleyce Elias|Gleice Elias|Gleici Elias", TEXT) ~ "Greyce Elias",
      grepl("Iracema Portella|Iracema Portela|Yracema Portela|Yracema Portella", TEXT) ~ "Iracema Portella",
      grepl("Jandira Feghali|sigajandira|jfeghali|jandira_feghali|Jandira Fegali|Jandhira Fegali|Jandhira Feghali", TEXT) ~ "Jandira Feghali",
      grepl("Jaqueline Cassol|jqcassol|Jaqueline Caçol|Jaqueline Casol", TEXT) ~ "Jaqueline Cassol",
      grepl("Jéssica Sales|jessicasalesdeputada|Jéssica Salles", TEXT) ~ "Jéssica Sales",
      grepl("Joênia Wapichana|Joênia Apichana|Joêna Apichana|Joêna Wapichana|Joenia Apixana|Joenia Wapixana|Joênia Uapichana", TEXT) ~ "Joênia Wapichana",
      grepl("Joice Hasselmann|joicehasselmannoficial|Joyce Hasselmann|Joyce Haselmann|Joyce Haselman|Joice Haselmann|Joice Haselman|Joice Hassellmman|Joice Halsemann|Joyce Halsemann|Joyce Hasselman", TEXT) ~ "Joice Hasselmann",
      grepl("Lauriete Malta|deputada.lauriete|Deputada Federal Lauriete|laurietecantora|Lauriette Malta|Lauriete Matta|Lauriete Mata|Laurete Malta", TEXT) ~ "Lauriete Malta",
      grepl("Leandre Dal Ponte|DeputadaLeandreDalPonte|leandredalponte|deputadaleandre|Leandre|Leandra Dal Ponte|Lenadra Dal Ponte|Leandre da Ponte", TEXT) ~ "Leandre Dal Ponte",
      grepl("Leda Sadala|dep_ledasadala|Leda Sadalla|Leda Salada", TEXT) ~ "Leda Sadala",
      grepl("Lídice da Mata|Lídice Mata|Lídice da Matta|Lídice Matta|Lidise da Mata", TEXT) ~ "Lídice da Mata",
      grepl("Liziane Bayer|lizianebayeroficial|Lizziane Bayer|Lizziane Baier|Lisiane Bayer|Lisiane Baier|Liziane Baier", TEXT) ~ "Liziane Bayer",
      grepl("Luisa Canziani|LuisaCanzianiOficial|Luiza Canziani|Luiza Cansiani|Luisa Cansiani|Luisa Canciani", TEXT) ~ "Luisa Canziani",
      grepl("Luiza Erundina|deputadluizaerundina|Luisa Erundina|Erundina|Luiza Erondina|Luisa Erondina", TEXT) ~ "Luiza Erundina",
      grepl("Magda Mofatto|magdamofatto.goias|Magda Mofato|Magda Mofado", TEXT) ~ "Magda Mofatto",
      grepl("Major Fabiana|majorfabianadepfed|Mj Fabiana|majorfabianadep", TEXT) ~ "Major Fabiana",
      grepl("Mara Rocha|mararochaoficial|mararocha4545|Deputada Mara Rocha", TEXT) ~ "Mara Rocha",
      grepl("Margarete Coelho|Margarette Coelho|Margarett Coelho|Margareth Coelho|Margareti Coelho|Margaret Coelho", TEXT) ~ "Margarete Coelho",
      grepl("Margarida Salomão|jfmargarida", TEXT) ~ "Margarida Salomão",
      grepl("Maria do Rosário|mariadorosariopt|Maria Rosário", TEXT) ~ "Maria do Rosário",
      grepl("Maria Rosas|mariarosas.oficial|mariarosassp", TEXT) ~ "Maria Rosas",
      grepl("Mariana Carvalho|marianacarvalho4545|DeputadaMariana|Maryana Carvalho|Marianna Carvalho", TEXT) ~ "Mariana Carvalho",
      grepl("Marília Arraes|MaríliaArraesPE|Marilia Arrais|Marílha Arrais|Marilha Arraes|Marilía Araes|Marília Arais", TEXT) ~ "Marília Arraes",
      grepl("Marina Santos|Dra Marina", TEXT) ~ "Marina Santos",
      grepl("Natália Bonavides|natbonavides|Nathalia Bonavides|Nathalya Bonavides|Natalya Bonavides|Natalia Bonavinde|Natalya Bonavinde|Nathalya Bonavinde|Nathalia Bonavinde|Natália Bonavide|Nathália Bonavide|Nathalya Bonavide|Natalya Bonavide", TEXT) ~ "Natália Bonavides",
      grepl("Norma Ayub|deputadanormaayub|Norma Aiub|Norma Ahiub|Norma Ahyub|Norma Pereira|Norma Perera", TEXT) ~ "Norma Ayub",
      grepl("Paula Belmonte|PaulaBelmonteoficial|Paulla Belmonte|Paula Beomonte|Paula Belmomte|Paula Belomonte|Paula Bellmonte|Paula Belmonti", TEXT) ~ "Paula Belmonte",
      grepl("Perpétua Almeida|deputadaperpetua|perpetua_acre|Perpétua Acre|Perpéta Acre|Perpéta Almeida", TEXT) ~ "Perpétua Almeida",
      grepl("Policial Katia Sastre|KatiaSastre|Catia Sastre|Katia Satre|Policial Catia Sastre|Policial Katia Satre", TEXT) ~ "Katia Sastre",
      grepl("Prof. Dayane Pimentel|professoradayanepimentel|deppimentel|Dayane Pimentel|Daiane Pimentel|Professora Daiane Pimentel|Professora Dayane Pimentel", TEXT) ~ "Dayane Pimentel",
      grepl("Prof. Marcivânia Flexa|profmarcivania|Marcivânia|Marcivâna|Professora Marcivâna|Marsivania|Marcilvânia Flecha", TEXT) ~ "Marcivânia Flexa",
      grepl("Professora Dorinha|profdorinha|Dorinha|Prof Dorinha", TEXT) ~ "Dorinha",
      grepl("Professora Rosa Neide|prof_rosaneide|Rosa Neide|Rosaneide|Prof. Rosa Neide|Rosa Neidi", TEXT) ~ "Rosa Neide",
      grepl("Rejane Dias|rejane_dias|Regiane Dias|Rejiani Dias", TEXT) ~ "Rejane Dias",
      grepl("Renata Abreu|renataabreu1919", TEXT) ~ "Renata Abreu",
      grepl("Rosana Valle|rosanavalleoficial|DepRosanaValle|Rosana Vale|Rosane Valle|Rosane Vale", TEXT) ~ "Rosana Valle",
      grepl("Rosângela Gomes|deputadarosangelagomes|rosangelasgomes", TEXT) ~ "Rosângela Gomes",
      grepl("Rose Modesto|rosemodestoms|Rose Modestto|Rosi Modesto", TEXT) ~ "Rose Modesto",
      grepl("Sâmia Bomfim|Sâmia Bonfim|Sâmia Bonfin|Sâmia Bomfin|Samia Bom Fim", TEXT) ~ "Sâmia Bomfim",
      grepl("Shéridan|sheridan4545|deputadasheridan|Shéridan Oliveira|DepSheridan|Séridan Oliveira|Cheridan Oliveira|Cheridan|Cheridam|Seridam|Sheridam|Sherydam|Sherida", TEXT) ~ "Shéridan",
      grepl("Silvia Cristina|silviacristina.ro|silviacristinax|Silvia Christina", TEXT) ~ "Silvia Cristina",
      grepl("Soraya Santos|Soraia Santos|dep.sorayasantos", TEXT) ~ "Soraya Santos",
      grepl("Tabata Amaral|tabataamaralsp|Thabata Amaral,Tabita Amaral|Taubata Amaral", TEXT) ~ "Tabata Amaral",
      grepl("Talíria Petrone|Taliria Petroni|Taliria|Talira Petrone|Talira Petroni|Talíria Peltrone|Talira Peltrone,", TEXT) ~ "Talíria Petrone",
      grepl("Tereza Nelma|terezanelmaal|Thereza Nelma|Theresa Nelma|Teresa Nelma|Tereza Neuma|Teresa Neuma", TEXT) ~ "Tereza Nelma",
      grepl("Tia Eron|Tia Erom|Eronilde Vasconcelos|Eronilde Vasconcellos", TEXT) ~ "Tia Eron",
      grepl("Vanda Milani|MilaniVanda|Vanda Millani|Wanda Milani|Wanda Millani|Dr. Vanda Milani", TEXT) ~ "Vanda Milani",
      grepl("Vivi Reis|vivireispsol|Viviane Reis", TEXT) ~ "Vivi Reis",
      grepl("Daniela Ribeiro|soudaniella111|daniellasenadora|Daniella Ribeiro|Daniella Ribero|Daniela Ribero|Danyela Ribeiro|Danyela Ribero", TEXT) ~ "Daniela Ribeiro",
      grepl("Eliziane Gama|Elziane Gama|Elsiane Gama|Elzeane Gama|Elseana Gama|Elisiane Gama|Elisiani Gama|Ellisiane Gama|Ellisiani Gama|Elliziane Gama|Elliziani Gama", TEXT) ~ "Eliziane Gama",
      grepl("Katia Abreu|senadorakatiaabreu|katiaabreuoficial|Catia Abreu", TEXT) ~ "Katia Abreu",
      grepl("Leila Barros|Leila do volei", TEXT) ~ "Leila Barros",
      grepl("Mailza Gomes|senadoramailzagomes|mailzagomes11|Mailsa Gomes|Maliza Gomes|Malisa Gomes", TEXT) ~ "Mailza Gomes",
      grepl("Maria do Carmo Alves|senadoramariadocarmo|MariaSenadora", TEXT) ~ "Maria do Carmo Alves",
      grepl("Nilda Gondim|senadoranildagondim|nildagondimpb|Nilda Gomdim|Nilda Gomdin", TEXT) ~ "Nilda Gondim",
      grepl("Simone Tebet|simonetebetms|Simone Tebeti|Simone Tebett", TEXT) ~ "Simone Tebet",
      grepl("Soraya Thronicke|senadorasorayathronicke|Soraia Thronicke|Soraya Tronicke|Soraya Trhonicke|Soraya Thronick|Soraya Thronic|Soraya Thronik|Soraia Tronicke|Soraia Trhonicke|Soraia Thronick|Soraia Thronic|Soraia Thronik", TEXT) ~ "Soraya Thronicke",
      grepl("Zenaide Maia|zenaidern|senadorazenaidemaia|Zenaide de maia", TEXT) ~ "Zenaide Maia",
      grepl("Rose de Freitas|senadorarosedefreitas|SenadoraRose|Rosy de Freitas|Rosi de Freitas", TEXT) ~ "Rose de Freitas",
      grepl("Mara Gabrilli|maragabrilli|Mara Gabrili|Mara Marili|Mara Gabili|Mara Gabyli|Mara Gabrylli|Mara Gabrilly|Mara Gabrily", TEXT) ~ "Mara Gabrilli",
      T ~ "Others")) %>% 
  filter(MENTION != "Others")
